outdir: branches/tracking/sidereal
n_obs: 3
n_demo: 0
n_sat: 1
seed: 57721

meta:
    branch: sidereal
    competitor_name: LLNL_dev
    display_true_name: True

# TODO: Get th, dthdr, and unvig from here: http://nesssi.cacr.caltech.edu/ZTF/Web/Calib.html

instrument:
    distortion:  # plate-scale (arcsec/micron) vs field angle (deg)
        th: &th [0.0, 1.0]
        dthdr: [0.05, 0.05]
    vignetting:  # surviving fraction vs field angle (deg)
        th: *th
        unvig: [1.0, 0.0]
    pixel_scale: 15 # microns
    image_shape: [6160, 6144]  # pixels
    gain: 6.2
    read_noise: 8
    aperture: 0.3691205  # m diameter
    obscuration: 0.224  # fractional linear

conditions:
    psf_fwhm_range: [2.0, 2.0]  # arcsec
    sky_range: [19.5, 20.8]  # mag/arcsec^2  (LSST is ~20.5)
    zp_range: [0.0, 0.35]  # wrt nominal

cadence:
    exptime: [30]

tracker:
    type: 'sidereal'
    rot_sky_pos0: 0.0
    error:
        v_perturb: 1.0  # and perturb the velocity by ~this amount
        boresight: 0.2  # As fraction of field radius
    jitter: 0.00139  # degree; corresponds to ~5 arcsec.


sites: ['Palomar']

sat:
    mag_range: [10.0, 13.0]
    size_range: [0.1, 10] # meters
    albedo_range: [0.05, 0.2]

catalog:
    develop: False
    gaia_dir: /p/lustre1/rearmstr/ref_cats/gaia_dr2_20200414/
    min_snr: 5.0
